spring:
  application:
    name: loanengine
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/loanengine?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:userpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

springdoc:
  swagger-ui:
    path: /swagger-ui.html
